### ISSUE TITLE
Be able to attach before starting a container

### ISSUE THREAD

**Issue by jakajancar** [almoehi/reactive-docker#5]
Hey,

AFAIK, you have to attach before starting a container, otherwise you risk losing some early data.

I'm not sure, but I think this API does not support this: you cannot know when you have successfully attached, since the Future `attachStream` returns never completes if the container is not running.

**Comment by almoehi** [comment]
Hi,
I agree, this is a pretty helpful use case.

I'm not sure if this usecase is supported by docker`s remote API at all (but I think so). 

As for reactive-docker, it should be possible. The futures should return upon receiving any response from the docker server. Now, I don't know the behavour of the docker server when attaching to a non-running container. Maybe it only sends some response when the container is being started.

I think we have to try this - will try to write a simple test case like this:
```
- create new container
- attach to container
- start container
```
is this the way you'd like it to work ?

**Comment by almoehi** [comment]
Ok, so this is the test case I came up with and which works fine with the current version of reactive-docker:

```
      env.containerId.id must not be empty
      val (it, en) = Concurrent.joined[Array[Byte]]
      val maybeRes = (en &> DockerEnumeratee.rawStream |>>> Iteratee.head)

      val attached = docker.attachStream(env.containerId, true, true, true)(it).flatMap(_.run)
      val run = await(docker.containerStart(env.containerId))

      val res = await(maybeRes)
      res must not be empty
      res.get.channel must be_==(0)
      res.get.text must be_==("hello world")
```
note:
You do not want to wait for the ```attached``` future to complete as this might never happen. You are attaching to a (possibly) infinite stream, so the future will never complete as the HTTP connection will never complete as well.

Instead, you should wait for your consumer iteratee to complete (if it is designed to complete)
Does this work for you ?

**Comment by jakajancar** [comment]
Haven't tested it yet, but yes, I think it should work.

Btw, create+attach+start is also how `docker run` works.
